#!/usr/bin/env bash
#in this script we use while to print best school except when i is  8 it prints both hi and best school
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]
         then
		echo "Best School"
		echo "Hi"
         else
		echo "Best School"
	fi
   i=$(( $i+1 ))
done
