#!/usr/bin/env bash
#in this script we use while to print best school except when i is  8 it prints both hi and best school
#shellcheck disable=SC2004
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
         then
		echo  "bad luck"
        elif [ $i -eq  7 ]
         then
                echo  "good luck" 
        else
		echo "Best School"
        fi
   i=$(( $i+1 ))
done
