#!/usr/bin/env bash 
#in this script we use case to print superstitious numbers and their origin countries
i="1"
while [ $i -lt  20 ]
do
	case $i in
		"4" ) echo "4"
		 echo "bad luck from China"
		;;
		"9" ) echo "9" 
		echo "bad luck from Japan"
		;;
		"17" ) echo "17" 
		echo "bad luck from Italy"
		 ;;
		 *  ) echo "$i"
		 ;;
	esac
i=$(( $i+1 ))
done
echo "20"		 
