#!/usr/bin/env bash
# in this script we use case to print superstitious numbers and their origin countries
# shellcheck disable=SC2004

i=1

while [ "$i" -lt 721 ]; do
    if (( i % 60 == 0 )); then
        echo "Hour: $(( i / 60 ))"
    else
        echo "$(( i % 60 ))"
    fi
    i=$(( i + 1 ))
done

