#!/usr/bin/env bash
#in this script we use trap and other commands to react to signals
echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 0' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT

i=0
while [ $i -ne 10 ]
do
    echo "To infinity and beyond"
done

rm -f /var/run/myscript.pid
exit 0
