#!/usr/bin/env bash
#comment
touch /var/run/myscript.pid
echo "$$">/var/run/myscript.pid
i=0
while [ $i != 10 ]
do
	echo "To infinity and beyond"
	sleep 2
done
trap 'echo "I hate the kill command" && rm /var/run/myscript.pid;exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit 0 ' SIGQUIT
